# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e99c3f3f7d8c0a801483d669485d3cacb29fd2f6e54340e50bf8c2414cc49a672a69f40f8889213a87e18b366e3850268871d81e70e9e64e863db3a8bbb3d29f

test:
  secret_key_base: bbcedcfbae4018c48547fd7a67b72b35ee2d49ef0ff26a1434d496406521c0dd4d178d104a5548d58e179c41b4d4f34b0f242be6eac0f2cc89f62bebd40ef0bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
